[package]
name = "coffeetime"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["full"] }

[dependencies.gtk]
package = "gtk4"
version = "0.10"
features = ["v4_2"]

[workspace]
members = [
    "daemon",
]
